### PR TITLE
language: fix French po file

### PR DESCRIPTION
**Pull request by saulery**
Hi Graeme,

A litle fix for fpGUI.

Regards,

### CODE REVIEW

**Comment by graemeg** [comment]
Thank you very much for your contribution. It is much appreciated.

**Comment by saulery** [comment]
Hello Graeme,

Nothing!

Regards,

**Comment by graemeg** [comment]
?? I'm lost.

**Comment by saulery** [comment]
Ok, it's not good word in English. It's a French word for : Very much.

**Comment by graemeg** [comment]
:+1:

**Pull request merged**
