### PR TITLE
Some updates and fixes

### PR DESCRIPTION
**Pull request by glixx**
Some updates and fixes

### CODE REVIEW

**Comment by glixx** [comment]
Ping

**Comment by glixx** [comment]
The second ping

**Comment by glixx** [comment]
Ping

**Comment by benohb** [comment]
I ping also

**Comment by graemeg** [comment]
Thanks for the reminder. I'm looking at it now. Just having some troubles generating the lang_*.inc files - they all end up being empty for some reason. As soon as that is resolved, I'll merge your commits.

**Comment by fredvs** [comment]
> Just having some troubles generating the lang_*.inc files - they all end up being empty for some reason

Hello Graeme.
Nothing to do with generating *.inc files but using {$I something.inc}.

In my projects that use {$I something.inc}, if I change something in the .inc file, I have to delete all the *.ppu and *.o files before to re-compile.

Strangely, even with -B parameter (re-built all), the changes done in the .inc file are not not taken into account.

It is a **very** old fpc bug, but still not fixed.

So maybe a comment about this would be welcome in readme.txt.

[EDIT] I ping also ;)

Fre;D

**Comment by glixx** [comment]
Any news?

**Comment by graemeg** [comment]
Sorry for the delay. I had some software issues and had to rebuild my development machine and then get the localize utilities updated.  All sorted. Thank you VERY much for all your contributions. It is very much appreciated.

**Comment by fredvs** [comment]
Hello Graeme.

Could you commit this for `maint` branch too?
Thnks..

**Comment by graemeg** [comment]
As far as I know the pull request was only against the "develop" branch. Not sure if it will merge in correctly into "maint", but I'll give it a go tonight.

**Comment by graemeg** [comment]
Sorry Fred, I tried, but it seems the "maint" and "develop" branches have diverged to much. I got tons of merge conflicts in every commit.

**Pull request merged**
