### PR TITLE
Removed unused FontConfig dependency in fpg_x11.pas and fpg_xft_x11.pas.

### PR DESCRIPTION
**Pull request by fredvs**
Hello.

Removed dependencies to fontconfig.so.
That dependency is not used.
Also, recently, fontconfig released fontconfig.so.3.
Sadly that new version is no compatible with previous version fontconfig.so.2. (different config files)

And with fpc you oblige people to install fontconfig-dev that will install the link fontconfig.so that point to fontconfig.so.3.

With some distros, like Manjaro, they still use fontconfig.so.2. and have no plan to upgrade to fontconfig.so.3. and it makes the system instable.

Once again a "academic" example how  fpc "external" and his strange code is not the best way to do.

Fre;D

### CODE REVIEW

**Comment by fredvs** [comment]
Last commit is the good one, previous used fpg_x11.pas and fpg_xft_x11.pas. from develop-branch.
This last commit use fpg_x11.pas and fpg_xft_x11.pas. from maint-branch.

**Comment by fredvs** [comment]
Ping!

**Comment by JonnyTech** [comment]
Good job @fredvs - just tried this patch on the `develop` branch it works ok with Linux 64 and ARM. @graemeg do you want a PR for `develop` too?

**Comment by graemeg** [comment]
Thank you Fred - this change has been committed in both `maint` and `develop`. I had to clean up the commits due to this pull request containing changes from both "develop" and "maint" branch. Either way, I made sure the commit Author is correctly set to your name.

**Pull request closed without merging**
