### PR TITLE
Fix JPEG issues

### PR DESCRIPTION
**Pull request by JonnyTech**
Not sure if I am doing this right as I am new to git, did try to make two separate pr's but both got merged.

### CODE REVIEW

**Comment by graemeg** [comment]
Many thanks, I've merged the "red shift fix" change. I've also applied a minor Alpha channel fix (for when rendering with AggPas).

TIP: In future, I suggest you apply such changes in separate feature or bugfix branches. This means each set of related changes are in separate branches. This makes it easier to merge upstream. It also means you will not get conflicts when you do your next pull.

**Comment by JonnyTech** [comment]
Thanks, that was my first ever git operation. Do you have any tips for a pascal user's workflow?

**Comment by graemeg** [comment]
I've merged the JPEGScale patch as well. Many thanks.

**Comment by graemeg** [comment]
Glad you are trying Git though - it really should be a vital tool for all software developers. For some tips, take a look at the **docs/git_howto.txt** document. The newsgroups also had multiple git discussions with examples, but I think the git_howto.txt should be a summary of that. There are tons of good tutorials and documentation on the internet too.

ps:
  If you get conflicts on your next Git pull (because you committed directly into the "develop" branch), then simply do a hard reset commit b62e3d47 and then do another pull. NOTE: a hard reset (git reset --hard <sha1>) will remove all local changes up to the commit you specified. So if you have more local changes, make sure you have a backup of them (eg: committed in a separate branch).

**Comment by JonnyTech** [comment]
I'm struggling with getting my repo synced with yours. Far too tired now, need some sleep. Is it easier if I delete my whole repo and refork or would that cause issues?

**Comment by graemeg** [comment]
I thought that was going to happen, hence I mentioned it in my previous messages. Note: You _never_ need to delete a git repository and clone it again. I is actually extremely hard to screw a git repository up with no possibility to recover it to a normal state.
It might be easier to explain this in the fpgui.support newsgroup, as text formatting is better there. So please refer to the newsgroup for my explanation.

**Pull request closed without merging**
