### PR TITLE
Clean up unused local variables

### PR DESCRIPTION
**Pull request by lkppo**
Hello Graeme,

Here is a small patch to clean conpilation of fpGUI.

I look at the code of fpGUI and I wonder if what is described in freepascal wiki is correct?

http://wiki.freepascal.org/Roadmap#Widgetset_dependent_components

Regards,

### CODE REVIEW

**Comment by graemeg** [comment]
Hi,

Many thanks for your contribution. I'll apply these shortly. 

As for the wiki page you mentioned. That page has terrible wording, and it is a common misconception that the reader things the feature relate to the specific widget toolkits. That wiki page relates to the **LCL Interface portions** that talks to the various GUI toolkit backends (GTK2, GTK3, fpGUI, Qt etc). **LCL-fpGUI does NOT reflect the features of fpGUI Toolkit.**

**Comment by lkppo** [comment]
Hi Graeme,

Le mardi 21 avril 2015 à 06:49:03, Graeme Geldenhuys a écrit :
> 
> Many thanks for your contribution. I'll apply these shortly.
>
> As for the wiki page you mentioned. That page has terrible wording, and
> it is a common misconception that the reader things the feature relate
> to the specific widget toolkits. That wiki page relates to the **LCL
> Interface portions** that talks to the various GUI toolkit backends (GTK2,
> GTK3, fpGUI, Qt etc). **LCL-fpGUI does NOT reflect the features of fpGUI
> Toolkit.**

Ok. I discovered Free Pascal and its ecosystem.

Can I use fpGUI without LCL?
Is this page is up to date for what it says * really *?
Is the level to help fpGUI high?

I have other questions but for now I'll look into the documentation
before fpGUI and avoid unnecessary questions.

Regards,

-- 
Stéphane Aulery

**Comment by graemeg** [comment]
The preferred method to use fpGUI Toolkit, is to use it directly, without LCL. Only then do you get the full benefit and features. fpGUI also doesn't force any specific development tools other that the Free Pascal Compiler. You can use any text editor or IDE to develop with fpGUI. fpGUI also includes its own stand-alone Visual Forms Designer, DocView (documentation viewer) and many demos. The website also shows how to integrate the UI Designer and DocView into various editors and IDE's. The repository also contains code templates and a Lazarus IDE add-on which can help you get a new project up and running very quickly.

For any further questions or support, please visit the official fpGUI support newsgroup. Details on how to access it can be found on the website [http://fpgui.sourceforge.net/support.shtml]

The LCL-fpGUI interface is still far from complete, and not ready for general use.

**Comment by lkppo** [comment]
Le mercredi 22 avril 2015 à 06:21:44, Graeme Geldenhuys a écrit :
>
> The preferred method to use fpGUI Toolkit, is to use it directly, without
> LCL. Only then do you get the full benefit and features. fpGUI also doesn't
> force any specific development tools other that the Free Pascal Compiler.
> You can use any text editor or IDE to develop with fpGUI. fpGUI also
> includes its own stand-alone Visual Forms Designer, DocView (documentation
> viewer) and many demos. The website also shows how to integrate the UI
> Designer and DocView into various editors and IDE's. The repository also
> contains code templates and a Lazarus IDE add-on which can help you get a
> new project up and running very quickly.

I'm not a fan of the Lazarus ergonomics. If there is another IDE using
fpGUI, I'd be happy to know it.


> For any further questions or support, please visit the official fpGUI
> support newsgroup. Details on how to access it can be found on the website
> [http://fpgui.sourceforge.net/support.shtml]
>
> The LCL-fpGUI interface is still far from complete, and not ready for
> general use.

Does A benefit apart easily change toolkit?

-- 
Stéphane Aulery

**Comment by graemeg** [comment]
> If there is another IDE using fpGUI, I'd be happy to know it.

I switch between various IDE's and editors as I work. Lazarus IDE (though with every new release it frustrates me more and more), MSEide, EditPad Pro [http://www.editpadpro.com/] and jEdit. I know of other developers that use Geany and Eclipse too. Like I said, you can use any IDE or Programmer's Editor. You can normally integrate the fpGUI tools via their "External Tools" functionality. EditPad Pro is actually very good and has brilliant features and well worth the small price. Even though EditPad Pro is a Windows program, I use it a lot under FreeBSD via WINE too - it runs perfectly.

fpGUI also includes its own IDE called Maximus (examples/apps/ide/ directory), but it is really more of an *advanced demo* at this point. It is yet to be decided if it will or must become a full featured IDE. I've created it specifically as an advanced demo (because all my large projects are closed source), but I've had requests to develop it further as a functioning IDE. Time is the issue though.

An example of DocView integration into various IDE's and Editors. [http://fpgui.sourceforge.net/docview_ide_integration.shtml]. The same can be done for the UI Designer and calling the  fpc compiler.

> Does A benefit apart easily change toolkit?

I'm not sure I understand the question. I've never had the need to switch toolkits since I started fpGUI back in 2006. I tried to use LCL in a commercial environment and it was terrible. I started fpGUI to solve all the issues I had, and it now does exactly what it should on all platforms. The problem with LCL is that it is very inconsistent due to the various interface backends, and each backend interface being at a different level of completeness. The LCL-Win32/Win64 is probably the most complete and all the others keep playing catch-up, but never actually gets there.

**Comment by graemeg** [comment]
Just thought I would mention... Based on this pull request, you are still using fpGUI v1.2. That's not a problem for this pull request, but I suggest you pull the latest code so it switches you to the v1.4 release 'master' branch. Even better, after you did a pull, **switch to the 'fixes_1.4' branch** which contains some extra fixes that appeared after the v1.4 release.

**Comment by graemeg** [comment]
Many thanks for the contribution. Merged into 'fixes_1.4' branch as commit b5f2bb6.  Tonight I'll merge these changes into the 'develop' branch as well.

**Comment by lkppo** [comment]
Le mercredi 22 avril 2015 à 08:10:03, Graeme Geldenhuys a écrit :
>
> Just thought I would mention... Based on this pull request, you are still
> using fpGUI v1.2. That's not a problem for this pull request, but I suggest
> you pull the latest code so it switches you to the v1.4 release 'master'
> branch. Even better, after you did a pull, **switch to the 'fixes_1.4'
> branch** which contains some extra fixes that appeared after the v1.4
> release.

I only looked at the code, compiled to test and decided to contribute a patch
just before the unexpected version change. I take all these valuable insights
into account. Thank you, Graeme.

-- 
Stéphane Aulery

**Pull request closed without merging**
