### PR TITLE
Fixes compilation errors

### PR DESCRIPTION
**Pull request by JonnyTech**
Correct usage of new CenterPoint

### CODE REVIEW

**Comment by graemeg** [comment]
Many thanks for reporting this and supplying a patch. I didn't apply your patch though, as there was a simpler solution. I also took this time to fix a few other issues with the gauge unit and get rid of the horrid WITH statement usage. The compilation error was resolved in commit 8aaedca5.

**Comment by graemeg** [comment]
PS: I'm in the process of setting up an automated build process for the whole of fpGUI (framework, demos, tools etc). So this should notify me instantly if any changes cause compilation errors anywhere else in the fpGUI repository.

**Comment by JonnyTech** [comment]
Cool, you make it look so easy!
Do I now delete my branch?
PS: I like WITH statements ;)

**Comment by graemeg** [comment]
> Cool, you make it look so easy!

I've been doing this for way to long! :)

> Do I now delete my branch?

Yes you can.

```
     git push <remote> :<branchname>
     git branch -D <branchname>
```

Git sometimes have odd looking commands. The first command says to replace <branchname> with nothing - thus, deleted. The second command deletes the local one you have on your system.

> PS: I like WITH statements ;)

Haha... rather you than me. Except for the most simpest of code, I find WITH statements hard to read and figure out. It also opens up the code to potential errors (programmer intended one thing, but compiler scope decided another). So I just try and avoid the whole mess. :)

**Pull request closed without merging**
